### ISSUE TITLE
Giá cả

### ISSUE THREAD

**Issue by trandinhnghiem2014676** [QBitGenZ/lv003-frontend#38]
![image](https://github.com/QBitGenZ/lv003-frontend/assets/125441730/1ab09882-e8d7-43fe-95f6-7d784ab5369f)
![image](https://github.com/QBitGenZ/lv003-frontend/assets/125441730/65de6b34-eb6a-4e58-a381-1f40c7e73633)
Lỗi không thống nhất giá giữa giỏ hàng và khi thanh toán

**Comment by nntruyen027** [comment]
Không thể hiện giá cuối cùng có số lượng 
![image](https://github.com/QBitGenZ/lv003-frontend/assets/89064690/32a4616e-a05d-4f09-bab8-36e3bdd7cb38)
